# fly.toml app configuration file generated for wild-shape-3425 on 2023-07-14T14:11:05+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wild-shape-3425"
primary_region = "sin"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[env]
  PORT = "3000"
